# Perfil desarrollo
server.port=8082
server.servlet.context-path=/msaServices

spring.datasource.url=jdbc:postgresql://localhost:5432/db_test
spring.datasource.username=postgres
spring.datasource.password=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/authorizationServer
spring.urls.find-user-by-identification=/mscServices/api/users/findUserByIdentification

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=debug
